version: 3

includes:
    shared:
        taskfile: hack/common/Taskfile_controller.yaml
        flatten: true
        excludes: [] # put task names in here which are overwritten in this file
        vars:
            CODE_DIRS: "{{.ROOT_DIR}}/cmd/..."
            COMPONENTS: crypto-edge-operator
            REPO_URL: https://github.com/openkcm/crypto-edge-operator
